package io.github.eladimany.spindle.ui.theme

import androidx.compose.ui.graphics.Color

// Spindle's own identity: deep indigo/violet, fixed regardless of the device wallpaper.
// Material You dynamic color was the source of the "old and grey" complaint — on a
// neutral wallpaper it desaturates the whole app to grey. This is a hand-authored
// Material 3 tonal scheme (not wallpaper-derived), so every surface stays intentional.

// Light scheme
val md_light_primary = Color(0xFF4B3FD1)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFE3DFFF)
val md_light_onPrimaryContainer = Color(0xFF160568)
val md_light_secondary = Color(0xFF5C5680)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFE4DFFF)
val md_light_onSecondaryContainer = Color(0xFF191436)
val md_light_tertiary = Color(0xFF8E4A62)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFFFD9E3)
val md_light_onTertiaryContainer = Color(0xFF3A0716)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFBF8FF)
val md_light_onBackground = Color(0xFF1B1B21)
val md_light_surface = Color(0xFFFBF8FF)
val md_light_onSurface = Color(0xFF1B1B21)
val md_light_surfaceVariant = Color(0xFFE4E1EC)
val md_light_onSurfaceVariant = Color(0xFF46464F)
val md_light_outline = Color(0xFF767680)
val md_light_outlineVariant = Color(0xFFC7C5D0)
val md_light_inverseSurface = Color(0xFF303036)
val md_light_inverseOnSurface = Color(0xFFF2EFF7)
val md_light_inversePrimary = Color(0xFFC3BFFF)
val md_light_surfaceDim = Color(0xFFDBD8E0)
val md_light_surfaceBright = Color(0xFFFBF8FF)
val md_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_light_surfaceContainerLow = Color(0xFFF5F2FA)
val md_light_surfaceContainer = Color(0xFFEFECF4)
val md_light_surfaceContainerHigh = Color(0xFFE9E6EE)
val md_light_surfaceContainerHighest = Color(0xFFE3E0E9)

// Dark scheme
val md_dark_primary = Color(0xFFC3BFFF)
val md_dark_onPrimary = Color(0xFF1E1770)
val md_dark_primaryContainer = Color(0xFF372F97)
val md_dark_onPrimaryContainer = Color(0xFFE3DFFF)
val md_dark_secondary = Color(0xFFC7C2EA)
val md_dark_onSecondary = Color(0xFF2E2A4D)
val md_dark_secondaryContainer = Color(0xFF444066)
val md_dark_onSecondaryContainer = Color(0xFFE4DFFF)
val md_dark_tertiary = Color(0xFFFFB1C8)
val md_dark_onTertiary = Color(0xFF5E1132)
val md_dark_tertiaryContainer = Color(0xFF7D2948)
val md_dark_onTertiaryContainer = Color(0xFFFFD9E3)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF131318)
val md_dark_onBackground = Color(0xFFE4E1E9)
val md_dark_surface = Color(0xFF131318)
val md_dark_onSurface = Color(0xFFE4E1E9)
val md_dark_surfaceVariant = Color(0xFF46464F)
val md_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_dark_outline = Color(0xFF918F9A)
val md_dark_outlineVariant = Color(0xFF46464F)
val md_dark_inverseSurface = Color(0xFFE4E1E9)
val md_dark_inverseOnSurface = Color(0xFF303036)
val md_dark_inversePrimary = Color(0xFF4B3FD1)
val md_dark_surfaceDim = Color(0xFF131318)
val md_dark_surfaceBright = Color(0xFF39383F)
val md_dark_surfaceContainerLowest = Color(0xFF0E0E13)
val md_dark_surfaceContainerLow = Color(0xFF1B1B21)
val md_dark_surfaceContainer = Color(0xFF1F1F25)
val md_dark_surfaceContainerHigh = Color(0xFF2A292F)
val md_dark_surfaceContainerHighest = Color(0xFF35343A)
